I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script
    show jeck sad (0.5)
Exception: Image 'jeck sad' does not accept attributes '(0.5)'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 27, in script
    show jeck sad (0.5)
  File "C:\Users\user\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\user\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "C:\Users\user\Downloads\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\user\Downloads\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\user\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "C:\Users\user\Downloads\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'jeck sad' does not accept attributes '(0.5)'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
suyeonsi 1.0
Sat Apr  8 18:24:21 2023
